package Proveedor;

/**
* Proveedor/ProveedorsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Proveedor.idl
* jueves 8 de noviembre de 2018 07:21:41 PM COT
*/

public final class ProveedorsHolder implements org.omg.CORBA.portable.Streamable
{
  public Proveedor.Proveedors value = null;

  public ProveedorsHolder ()
  {
  }

  public ProveedorsHolder (Proveedor.Proveedors initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Proveedor.ProveedorsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Proveedor.ProveedorsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Proveedor.ProveedorsHelper.type ();
  }

}
