package Proveedor;


/**
* Proveedor/ProveedorsOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Proveedor.idl
* jueves 8 de noviembre de 2018 07:21:41 PM COT
*/

public interface ProveedorsOperations 
{
  boolean insertarProveedor (int Nit, String nombre, String apellidos, String direccion, String telefono);
  boolean actualizarProveedor (int Nit, String nombre, String apellidos, String direccion, String telefono);
  boolean eliminarProveedor (int Nit);
  String consultarProveedor (int Nit);
  void shoutdown ();
} // interface ProveedorsOperations
