package Proveedor;


/**
* Proveedor/Proveedors.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Proveedor.idl
* jueves 8 de noviembre de 2018 07:21:41 PM COT
*/

public interface Proveedors extends ProveedorsOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Proveedors
