package Proveedor;


/**
* Proveedor/ProveedorsPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Proveedor.idl
* jueves 8 de noviembre de 2018 07:21:41 PM COT
*/

public abstract class ProveedorsPOA extends org.omg.PortableServer.Servant
 implements Proveedor.ProveedorsOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("insertarProveedor", new java.lang.Integer (0));
    _methods.put ("actualizarProveedor", new java.lang.Integer (1));
    _methods.put ("eliminarProveedor", new java.lang.Integer (2));
    _methods.put ("consultarProveedor", new java.lang.Integer (3));
    _methods.put ("shoutdown", new java.lang.Integer (4));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Proveedor/Proveedors/insertarProveedor
       {
         int Nit = in.read_long ();
         String nombre = in.read_wstring ();
         String apellidos = in.read_wstring ();
         String direccion = in.read_wstring ();
         String telefono = in.read_wstring ();
         boolean $result = false;
         $result = this.insertarProveedor (Nit, nombre, apellidos, direccion, telefono);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // Proveedor/Proveedors/actualizarProveedor
       {
         int Nit = in.read_long ();
         String nombre = in.read_wstring ();
         String apellidos = in.read_wstring ();
         String direccion = in.read_wstring ();
         String telefono = in.read_wstring ();
         boolean $result = false;
         $result = this.actualizarProveedor (Nit, nombre, apellidos, direccion, telefono);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 2:  // Proveedor/Proveedors/eliminarProveedor
       {
         int Nit = in.read_long ();
         boolean $result = false;
         $result = this.eliminarProveedor (Nit);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 3:  // Proveedor/Proveedors/consultarProveedor
       {
         int Nit = in.read_long ();
         String $result = null;
         $result = this.consultarProveedor (Nit);
         out = $rh.createReply();
         out.write_wstring ($result);
         break;
       }

       case 4:  // Proveedor/Proveedors/shoutdown
       {
         this.shoutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Proveedor/Proveedors:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Proveedors _this() 
  {
    return ProveedorsHelper.narrow(
    super._this_object());
  }

  public Proveedors _this(org.omg.CORBA.ORB orb) 
  {
    return ProveedorsHelper.narrow(
    super._this_object(orb));
  }


} // class ProveedorsPOA
