package Proveedor;


/**
* Proveedor/ProveedorsHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Proveedor.idl
* jueves 8 de noviembre de 2018 07:21:41 PM COT
*/

abstract public class ProveedorsHelper
{
  private static String  _id = "IDL:Proveedor/Proveedors:1.0";

  public static void insert (org.omg.CORBA.Any a, Proveedor.Proveedors that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Proveedor.Proveedors extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (Proveedor.ProveedorsHelper.id (), "Proveedors");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Proveedor.Proveedors read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_ProveedorsStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Proveedor.Proveedors value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static Proveedor.Proveedors narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Proveedor.Proveedors)
      return (Proveedor.Proveedors)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Proveedor._ProveedorsStub stub = new Proveedor._ProveedorsStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static Proveedor.Proveedors unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Proveedor.Proveedors)
      return (Proveedor.Proveedors)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Proveedor._ProveedorsStub stub = new Proveedor._ProveedorsStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
