package Pedidos;


/**
* Pedidos/PedidoPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Pedidos.idl
* miércoles 7 de noviembre de 2018 11:35:09 AM COT
*/

public abstract class PedidoPOA extends org.omg.PortableServer.Servant
 implements Pedidos.PedidoOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("insertarPedidos", new java.lang.Integer (0));
    _methods.put ("actualizarPediso", new java.lang.Integer (1));
    _methods.put ("eliminarPedidos", new java.lang.Integer (2));
    _methods.put ("consultarPedidos", new java.lang.Integer (3));
    _methods.put ("shoutdown", new java.lang.Integer (4));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Pedidos/Pedido/insertarPedidos
       {
         int idCliente = in.read_long ();
         String nombre = in.read_wstring ();
         String direccion = in.read_wstring ();
         String telefono = in.read_wstring ();
         String estado = in.read_wstring ();
         boolean $result = false;
         $result = this.insertarPedidos (idCliente, nombre, direccion, telefono, estado);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // Pedidos/Pedido/actualizarPediso
       {
         int idPedidos = in.read_long ();
         int idClientes = in.read_long ();
         String nombre = in.read_wstring ();
         String direccion = in.read_wstring ();
         String telefono = in.read_wstring ();
         String estado = in.read_wstring ();
         boolean $result = false;
         $result = this.actualizarPediso (idPedidos, idClientes, nombre, direccion, telefono, estado);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 2:  // Pedidos/Pedido/eliminarPedidos
       {
         int idPedidos = in.read_long ();
         boolean $result = false;
         $result = this.eliminarPedidos (idPedidos);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 3:  // Pedidos/Pedido/consultarPedidos
       {
         int idPedidos = in.read_long ();
         String $result = null;
         $result = this.consultarPedidos (idPedidos);
         out = $rh.createReply();
         out.write_wstring ($result);
         break;
       }

       case 4:  // Pedidos/Pedido/shoutdown
       {
         this.shoutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Pedidos/Pedido:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Pedido _this() 
  {
    return PedidoHelper.narrow(
    super._this_object());
  }

  public Pedido _this(org.omg.CORBA.ORB orb) 
  {
    return PedidoHelper.narrow(
    super._this_object(orb));
  }


} // class PedidoPOA
