package Pedidos;


/**
* Pedidos/PedidoOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Pedidos.idl
* miércoles 7 de noviembre de 2018 11:35:09 AM COT
*/

public interface PedidoOperations 
{
  boolean insertarPedidos (int idCliente, String nombre, String direccion, String telefono, String estado);
  boolean actualizarPediso (int idPedidos, int idClientes, String nombre, String direccion, String telefono, String estado);
  boolean eliminarPedidos (int idPedidos);
  String consultarPedidos (int idPedidos);
  void shoutdown ();
} // interface PedidoOperations
