package Pedidos;


/**
* Pedidos/Pedido.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Pedidos.idl
* miércoles 7 de noviembre de 2018 11:35:09 AM COT
*/

public interface Pedido extends PedidoOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Pedido
