package Productos;


/**
* Productos/ProductoOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Productos.idl
* jueves 8 de noviembre de 2018 02:34:56 PM COT
*/

public interface ProductoOperations 
{
  boolean insertarProductos (int Codigo, String descripcion, String tipo, String cantidad, String valor);
  boolean actualizarProductos (int Codigo, String descripcion, String tipo, String cantidad, String valor);
  boolean eliminarProductos (int Codigo);
  String consultarProductos (int Codigo);
  void shoutdown ();
} // interface ProductoOperations
