package Productos;


/**
* Productos/Producto.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Productos.idl
* jueves 8 de noviembre de 2018 02:34:56 PM COT
*/

public interface Producto extends ProductoOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Producto
