package Empleados;


/**
* Empleados/Empleado.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Empleado.idl
* sábado 3 de noviembre de 2018 04:07:40 PM COT
*/

public interface Empleado extends EmpleadoOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Empleado
