package Empleados;


/**
* Empleados/EmpleadoOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Empleado.idl
* sábado 3 de noviembre de 2018 04:07:40 PM COT
*/

public interface EmpleadoOperations 
{
  boolean insertarEmpleado (int cedula, String nombre, String apellido, String telefono, String genero, String cargo);
  boolean actualizarEmpleado (int cedula, String nombre, String apellido, String telefono, String genero, String cargo);
  boolean eliminarEmpleado (int cedula);
  String consultarEmpleado (int cedula);
  void shoutdown ();
} // interface EmpleadoOperations
