
package Diseños;

 import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import CRUD.*;
import java.sql.ResultSet;
import java.sql.SQLException;

public class Informe extends javax.swing.JFrame {

    /**
     * Creates new form Informe
     */
    private DefaultTableModel modelo;
    public Informe() {
        initComponents();
        this.setLocationRelativeTo(null);   
        this.setSize(780, 450);
    }
     //Agragamos las columnas a nuestra Tabla Empleados
    private void mostrarColumnaEmpleado(){
        modelo = (DefaultTableModel) tblInforme.getModel();
        
        modelo.addColumn("CC");
        modelo.addColumn("NOMBRE");
        modelo.addColumn("APELLIDO");
        modelo.addColumn("TELEFONO");
        modelo.addColumn("GENERO");
        modelo.addColumn("CARGO");
    }
   private void cargarRegistroEmpleado(){
        
        Empleados objEmpleado = new Empleados();
        
        modelo = (DefaultTableModel) tblInforme.getModel();
        
        ResultSet resultado = objEmpleado.cargarEmpleado();
        
        try {
            Object datos[] = new Object[6];
            while (resultado.next()) {
                for (int i = 0; i < 6; i++) {
                    datos[i] = resultado.getObject(i + 1);
                }
                modelo.addRow(datos);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error" + e.getMessage());
        }
           
   }
     //Agragamos las columnas a nuestra Tabla Pedidos
    private void mostrarColumnaPedidos(){
        modelo = (DefaultTableModel) tblInforme.getModel();
        
        modelo.addColumn("ID.PEDIDOS");
        modelo.addColumn("ID.CLIENTES");
        modelo.addColumn("NOMBRE");
        modelo.addColumn("DIRECCION");
        modelo.addColumn("TELEFONO");
        modelo.addColumn("ESTADO");
    }
   private void cargarRegistroPedidos(){
        
        Pedido objPedido = new Pedido();
        
        modelo = (DefaultTableModel) tblInforme.getModel();
        
        ResultSet resultado = objPedido.cargarPedidos();
        
        try {
            Object datos[] = new Object[6];
            while (resultado.next()) {
                for (int i = 0; i < 6; i++) {
                    datos[i] = resultado.getObject(i + 1);
                }
                modelo.addRow(datos);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error" + e.getMessage());
        }
           
   }
   
   //Agragamos las columnas a nuestra Tabla Producto
    private void mostrarColumnaProducto(){
        modelo = (DefaultTableModel) tblInforme.getModel();
        
        modelo.addColumn("CODIGO");
        modelo.addColumn("FECHA INGRESO");
        modelo.addColumn("TIPO");
        modelo.addColumn("CANTIDAD");
        modelo.addColumn("VALOR");
       
    }
   private void cargarRegistroProducto(){
        
        Productos objProducto = new Productos();
        
        modelo = (DefaultTableModel) tblInforme.getModel();
        
        ResultSet resultado = objProducto.cargarProductos();
        
        try {
            Object datos[] = new Object[5];
            while (resultado.next()) {
                for (int i = 0; i < 5; i++) {
                    datos[i] = resultado.getObject(i + 1);
                }
                modelo.addRow(datos);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error" + e.getMessage());
        }
           
   }
    //Agragamos las columnas a nuestra Tabla Proveedores
    private void mostrarColumnaProveedor(){
        modelo = (DefaultTableModel) tblInforme.getModel();
        
        modelo.addColumn("NIT");
        modelo.addColumn("NOMBRE");
        modelo.addColumn("APELLIDO");
        modelo.addColumn("DIRECCION");
        modelo.addColumn("TELEFONO");
       
    }
   private void cargarRegistroProveedor(){
        
        Proveedores objProveedores = new Proveedores();
        
        modelo = (DefaultTableModel) tblInforme.getModel();
        
        ResultSet resultado = objProveedores.cargarProveedores();
        
        try {
            Object datos[] = new Object[5];
            while (resultado.next()) {
                for (int i = 0; i < 5; i++) {
                    datos[i] = resultado.getObject(i + 1);
                }
                modelo.addRow(datos);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error" + e.getMessage());
        }
           
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblInforme = new javax.swing.JTable();
        btnemp = new javax.swing.JButton();
        btnpedi = new javax.swing.JButton();
        btnprod = new javax.swing.JButton();
        btnprove = new javax.swing.JButton();
        btnsalir = new javax.swing.JButton();
        btnmenprincipal = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("INFORME DETALLADO");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(290, 20, 210, 50);

        tblInforme.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblInforme);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(50, 90, 680, 150);

        btnemp.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnemp.setText("EMPLEADOS");
        btnemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnempActionPerformed(evt);
            }
        });
        getContentPane().add(btnemp);
        btnemp.setBounds(100, 280, 110, 23);

        btnpedi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnpedi.setText("PEDIDOS");
        btnpedi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpediActionPerformed(evt);
            }
        });
        getContentPane().add(btnpedi);
        btnpedi.setBounds(240, 280, 100, 23);

        btnprod.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnprod.setText("PRODUCTOS");
        btnprod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprodActionPerformed(evt);
            }
        });
        getContentPane().add(btnprod);
        btnprod.setBounds(470, 280, 120, 23);

        btnprove.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnprove.setText("PROVEEDORES");
        btnprove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnproveActionPerformed(evt);
            }
        });
        getContentPane().add(btnprove);
        btnprove.setBounds(610, 280, 130, 23);

        btnsalir.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnsalir.setText("SALIR");
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnsalir);
        btnsalir.setBounds(230, 380, 65, 23);

        btnmenprincipal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnmenprincipal.setText("MENU PRINCIPAL");
        btnmenprincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnmenprincipalMouseClicked(evt);
            }
        });
        getContentPane().add(btnmenprincipal);
        btnmenprincipal.setBounds(490, 370, 130, 23);

        jButton1.setText("LIMPIAR TABLA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(350, 330, 120, 23);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/org-fondo-madera-negro.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 770, 430);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        System.exit(WIDTH);
    }//GEN-LAST:event_btnsalirActionPerformed

    private void btnmenprincipalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnmenprincipalMouseClicked
        MENU MN = new MENU();
           MN .setVisible(true);
           dispose();
    }//GEN-LAST:event_btnmenprincipalMouseClicked

    private void btnempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnempActionPerformed
         mostrarColumnaEmpleado();
         cargarRegistroEmpleado();
    }//GEN-LAST:event_btnempActionPerformed

    private void btnpediActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpediActionPerformed
         mostrarColumnaPedidos();
         cargarRegistroPedidos();
    }//GEN-LAST:event_btnpediActionPerformed

    private void btnprodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprodActionPerformed
         mostrarColumnaProducto();
         cargarRegistroProducto();
    }//GEN-LAST:event_btnprodActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        modelo.setColumnCount(0);
        modelo.setRowCount(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnproveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnproveActionPerformed
        mostrarColumnaProveedor();
        cargarRegistroProveedor();
    }//GEN-LAST:event_btnproveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Informe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Informe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Informe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Informe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Informe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnemp;
    private javax.swing.JButton btnmenprincipal;
    private javax.swing.JButton btnpedi;
    private javax.swing.JButton btnprod;
    private javax.swing.JButton btnprove;
    private javax.swing.JButton btnsalir;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblInforme;
    // End of variables declaration//GEN-END:variables
}
