/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Diseños;

/**
 *
 * @author DFVAL
 */
public class MENU extends javax.swing.JFrame {

    /**
     * Creates new form MENU
     */
    public MENU() {
        initComponents();
        this.setLocationRelativeTo(null);   
        this.setSize(600, 450);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnagregarempleado = new javax.swing.JButton();
        btnagregarpedidos = new javax.swing.JButton();
        btnagregarproveedor = new javax.swing.JButton();
        btnagregarproducto = new javax.swing.JButton();
        btnverregistro = new javax.swing.JButton();
        btnsalir = new javax.swing.JButton();
        btncsesion = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("¿ QUE DESEAS HACER ?");
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(130, 40, 300, 60);

        btnagregarempleado.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnagregarempleado.setText("AGREGAR EMPLEADO");
        btnagregarempleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnagregarempleadoMouseClicked(evt);
            }
        });
        getContentPane().add(btnagregarempleado);
        btnagregarempleado.setBounds(50, 140, 160, 30);

        btnagregarpedidos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnagregarpedidos.setText("AGREGAR PEDIDOS");
        btnagregarpedidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnagregarpedidosMouseClicked(evt);
            }
        });
        getContentPane().add(btnagregarpedidos);
        btnagregarpedidos.setBounds(50, 200, 160, 30);

        btnagregarproveedor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnagregarproveedor.setText("AGREGAR PROVEEDOR");
        btnagregarproveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnagregarproveedorMouseClicked(evt);
            }
        });
        getContentPane().add(btnagregarproveedor);
        btnagregarproveedor.setBounds(360, 140, 180, 30);

        btnagregarproducto.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnagregarproducto.setText("AGREGAR PRODUTO");
        btnagregarproducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnagregarproductoMouseClicked(evt);
            }
        });
        getContentPane().add(btnagregarproducto);
        btnagregarproducto.setBounds(360, 210, 180, 30);

        btnverregistro.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnverregistro.setText("VER REGISTROS");
        btnverregistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnverregistroMouseClicked(evt);
            }
        });
        getContentPane().add(btnverregistro);
        btnverregistro.setBounds(220, 270, 140, 30);

        btnsalir.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnsalir.setText("SALIR");
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnsalir);
        btnsalir.setBounds(50, 360, 80, 30);

        btncsesion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btncsesion.setText("CERRAR SESION");
        btncsesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btncsesionMouseClicked(evt);
            }
        });
        getContentPane().add(btncsesion);
        btncsesion.setBounds(400, 360, 150, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/org-fondo-madera-negro.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 0, 580, 410);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnagregarempleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnagregarempleadoMouseClicked
        Empleado Em = new Empleado();
           Em .setVisible(true);
           dispose();
    }//GEN-LAST:event_btnagregarempleadoMouseClicked

    private void btnagregarproveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnagregarproveedorMouseClicked
        Proveedor Prove = new Proveedor();
           Prove .setVisible(true);
           dispose();
    }//GEN-LAST:event_btnagregarproveedorMouseClicked

    private void btnagregarpedidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnagregarpedidosMouseClicked
        Pedidos Pedi = new Pedidos();
           Pedi .setVisible(true);
           dispose();
    }//GEN-LAST:event_btnagregarpedidosMouseClicked

    private void btnagregarproductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnagregarproductoMouseClicked
        Producto Pro = new Producto();
           Pro .setVisible(true);
           dispose();
    }//GEN-LAST:event_btnagregarproductoMouseClicked

    private void btnverregistroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnverregistroMouseClicked
        Informe Inf = new Informe();
           Inf .setVisible(true);
           dispose();
    }//GEN-LAST:event_btnverregistroMouseClicked

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        System.exit(WIDTH);
    }//GEN-LAST:event_btnsalirActionPerformed

    private void btncsesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncsesionMouseClicked
       Login Log = new Login();
           Log .setVisible(true);
           dispose();
    }//GEN-LAST:event_btncsesionMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MENU().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnagregarempleado;
    private javax.swing.JButton btnagregarpedidos;
    private javax.swing.JButton btnagregarproducto;
    private javax.swing.JButton btnagregarproveedor;
    private javax.swing.JButton btncsesion;
    private javax.swing.JButton btnsalir;
    private javax.swing.JButton btnverregistro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
