/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Diseños;
    import javax.swing.JOptionPane;
    import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DFVAL
 */
public class Pedidos extends javax.swing.JFrame {
     DefaultTableModel model = new DefaultTableModel();
    /**
     * Creates new form Pedidos
     */
    public Pedidos() {
        initComponents();
        this.setLocationRelativeTo(null);   
        this.setSize(800, 580);
        
        //CREAMOS COLUMNAS DE NUESTRA TABLA
        model.addColumn("ID.PEDIDOS");
        model.addColumn("ID.CLIENTES");
        model.addColumn("NOMBRE");
        model.addColumn("DIRECCION");
        model.addColumn("TELEFONO");
        
        this.tabladedatos.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtidped = new javax.swing.JTextField();
        txtidclie = new javax.swing.JTextField();
        txtnom = new javax.swing.JTextField();
        txtdir = new javax.swing.JTextField();
        txttel = new javax.swing.JTextField();
        btnregistrar = new javax.swing.JButton();
        btnbuscarempleado = new javax.swing.JButton();
        btneliminarempleado = new javax.swing.JButton();
        btnsalir = new javax.swing.JButton();
        btnmenuprincipal = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabladedatos = new javax.swing.JTable();
        btnlimpiarcampos = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PEDIDOS");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(120, 40, 130, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("NOMBRE");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 200, 80, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 255));
        jLabel4.setText("ID.PEDIDOS");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 110, 120, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 255));
        jLabel5.setText("ID.CLIENTES");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 160, 100, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 255));
        jLabel6.setText("DIRECCION");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 240, 100, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 255));
        jLabel7.setText("TELEFONO");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 280, 80, 20);
        getContentPane().add(txtidped);
        txtidped.setBounds(140, 110, 180, 30);

        txtidclie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidclieActionPerformed(evt);
            }
        });
        getContentPane().add(txtidclie);
        txtidclie.setBounds(140, 150, 180, 30);
        getContentPane().add(txtnom);
        txtnom.setBounds(140, 190, 180, 30);
        getContentPane().add(txtdir);
        txtdir.setBounds(140, 230, 180, 30);
        getContentPane().add(txttel);
        txttel.setBounds(140, 270, 180, 30);

        btnregistrar.setText("REGISTRAR");
        btnregistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregistrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnregistrar);
        btnregistrar.setBounds(350, 160, 100, 30);

        btnbuscarempleado.setText("BUSCAR");
        getContentPane().add(btnbuscarempleado);
        btnbuscarempleado.setBounds(480, 160, 110, 30);

        btneliminarempleado.setText("ELIMINAR");
        btneliminarempleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btneliminarempleadoMouseClicked(evt);
            }
        });
        btneliminarempleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarempleadoActionPerformed(evt);
            }
        });
        getContentPane().add(btneliminarempleado);
        btneliminarempleado.setBounds(620, 160, 110, 30);

        btnsalir.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnsalir.setText("SALIR");
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnsalir);
        btnsalir.setBounds(250, 490, 80, 30);

        btnmenuprincipal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnmenuprincipal.setText("MENU PRINCIPAL");
        btnmenuprincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnmenuprincipalMouseClicked(evt);
            }
        });
        getContentPane().add(btnmenuprincipal);
        btnmenuprincipal.setBounds(440, 490, 150, 30);

        tabladedatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabladedatos);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 330, 730, 140);

        btnlimpiarcampos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnlimpiarcampos.setText("LIMPIAR CAMPOS");
        btnlimpiarcampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimpiarcamposActionPerformed(evt);
            }
        });
        getContentPane().add(btnlimpiarcampos);
        btnlimpiarcampos.setBounds(470, 223, 140, 30);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/org-fondo-madera-negro.jpg"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 0, 810, 540);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtidclieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidclieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidclieActionPerformed

    private void btnregistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistrarActionPerformed
       String []registrar = new String[6];
      registrar[0]=txtidped.getText();
      registrar[1]=txtidclie.getText();
      registrar[2]=txtnom.getText();
      registrar[3]=txtdir.getText();
      registrar[3]=txttel.getText();
  
      model.addRow(registrar);
    }//GEN-LAST:event_btnregistrarActionPerformed

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        System.exit(WIDTH);
    }//GEN-LAST:event_btnsalirActionPerformed

    private void btnmenuprincipalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnmenuprincipalMouseClicked
        MENU MN = new MENU();
        MN .setVisible(true);
        dispose();
    }//GEN-LAST:event_btnmenuprincipalMouseClicked

    private void btnlimpiarcamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimpiarcamposActionPerformed
        txtidped.setText("");
        txtidclie.setText("");
        txtnom.setText("");
        txtdir.setText("");
        txttel.setText("");
    }//GEN-LAST:event_btnlimpiarcamposActionPerformed

    private void btneliminarempleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarempleadoActionPerformed
       
    }//GEN-LAST:event_btneliminarempleadoActionPerformed

    private void btneliminarempleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btneliminarempleadoMouseClicked
         int eli=tabladedatos.getSelectedRowCount();
       if(eli>=0){
           model.removeRow(eli);
       }else{
           JOptionPane.showMessageDialog(null,"No Hay Datos Que Eliminar");
       }
    }//GEN-LAST:event_btneliminarempleadoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pedidos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbuscarempleado;
    private javax.swing.JButton btneliminarempleado;
    private javax.swing.JButton btnlimpiarcampos;
    private javax.swing.JButton btnmenuprincipal;
    private javax.swing.JButton btnregistrar;
    private javax.swing.JButton btnsalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabladedatos;
    private javax.swing.JTextField txtdir;
    private javax.swing.JTextField txtidclie;
    private javax.swing.JTextField txtidped;
    private javax.swing.JTextField txtnom;
    private javax.swing.JTextField txttel;
    // End of variables declaration//GEN-END:variables
}
