/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Diseños;
   import javax.swing.JOptionPane;
    import javax.swing.table.DefaultTableModel;
/**
 *
 * @author DFVAL
 */
public class Proveedor extends javax.swing.JFrame {
   DefaultTableModel model = new DefaultTableModel();
    /**
     * Creates new form Proveedor
     */
    public Proveedor() {
        initComponents();
        this.setLocationRelativeTo(null);   
        this.setSize(800, 580);
        
        //CREAMOS COLUMNAS DE NUESTRA TABLA
        model.addColumn("NIT");
        model.addColumn("NOMBRE");
        model.addColumn("APELLIDOS");
        model.addColumn("DIRECCION");
        model.addColumn("TELEFONO");
        
        this.tabladedatos.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txttel = new javax.swing.JTextField();
        txtnit = new javax.swing.JTextField();
        txtnom = new javax.swing.JTextField();
        txtape = new javax.swing.JTextField();
        txtdir = new javax.swing.JTextField();
        btnregistrar = new javax.swing.JButton();
        btnconsultarproveedor = new javax.swing.JButton();
        btneliminarproveedor = new javax.swing.JButton();
        btnsalir = new javax.swing.JButton();
        btnmenuprincipal = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabladedatos = new javax.swing.JTable();
        btnlimpiardatos = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/org-fondo-madera-negro.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PROVEEDOR");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(110, 50, 130, 22);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 255));
        jLabel3.setText("TELEFONO");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 270, 90, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 255));
        jLabel4.setText("NIT");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 110, 73, 17);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 255));
        jLabel5.setText("NOMBRE");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 150, 75, 17);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 255));
        jLabel6.setText("APELLIDOS");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 190, 90, 17);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 255));
        jLabel7.setText("DIRECCION");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 230, 90, 17);
        getContentPane().add(txttel);
        txttel.setBounds(150, 260, 160, 30);
        getContentPane().add(txtnit);
        txtnit.setBounds(150, 100, 160, 30);
        getContentPane().add(txtnom);
        txtnom.setBounds(150, 140, 160, 30);

        txtape.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtapeActionPerformed(evt);
            }
        });
        getContentPane().add(txtape);
        txtape.setBounds(150, 180, 160, 30);
        getContentPane().add(txtdir);
        txtdir.setBounds(150, 220, 160, 30);

        btnregistrar.setText("REGISTRAR");
        btnregistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregistrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnregistrar);
        btnregistrar.setBounds(350, 150, 100, 30);

        btnconsultarproveedor.setText("CONSULTAR");
        getContentPane().add(btnconsultarproveedor);
        btnconsultarproveedor.setBounds(480, 150, 110, 30);

        btneliminarproveedor.setText("ELIMINAR");
        btneliminarproveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btneliminarproveedorMouseClicked(evt);
            }
        });
        btneliminarproveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarproveedorActionPerformed(evt);
            }
        });
        getContentPane().add(btneliminarproveedor);
        btneliminarproveedor.setBounds(610, 150, 110, 30);

        btnsalir.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnsalir.setText("SALIR");
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnsalir);
        btnsalir.setBounds(240, 500, 90, 30);

        btnmenuprincipal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnmenuprincipal.setText("MENU PRINCIPAL");
        btnmenuprincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnmenuprincipalMouseClicked(evt);
            }
        });
        getContentPane().add(btnmenuprincipal);
        btnmenuprincipal.setBounds(440, 500, 130, 30);

        tabladedatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabladedatos);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(50, 330, 680, 150);

        btnlimpiardatos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnlimpiardatos.setText("LIMPIAR DATOS");
        btnlimpiardatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimpiardatosActionPerformed(evt);
            }
        });
        getContentPane().add(btnlimpiardatos);
        btnlimpiardatos.setBounds(460, 220, 140, 30);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/org-fondo-madera-negro.jpg"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 0, 780, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtapeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtapeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtapeActionPerformed

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
       System.exit(WIDTH);
    }//GEN-LAST:event_btnsalirActionPerformed

    private void btnmenuprincipalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnmenuprincipalMouseClicked
       MENU MN = new MENU();
           MN .setVisible(true);
           dispose();
    }//GEN-LAST:event_btnmenuprincipalMouseClicked

    private void btneliminarproveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarproveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btneliminarproveedorActionPerformed

    private void btnregistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistrarActionPerformed
        String []registrar = new String[6];
      registrar[0]=txtnit.getText();
      registrar[1]=txtnom.getText();
      registrar[2]=txtape.getText();
      registrar[3]=txtdir.getText();
      registrar[3]=txttel.getText();
  
      model.addRow(registrar);
    }//GEN-LAST:event_btnregistrarActionPerformed

    private void btnlimpiardatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimpiardatosActionPerformed
        txtnit.setText("");
        txtnom.setText("");
        txtape.setText("");
        txtdir.setText("");
        txttel.setText("");
    }//GEN-LAST:event_btnlimpiardatosActionPerformed

    private void btneliminarproveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btneliminarproveedorMouseClicked
        int eli=tabladedatos.getSelectedRowCount();
       if(eli>=0){
           model.removeRow(eli);
       }else{
           JOptionPane.showMessageDialog(null,"No Hay Datos Que Eliminar");
       }
    }//GEN-LAST:event_btneliminarproveedorMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Proveedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnconsultarproveedor;
    private javax.swing.JButton btneliminarproveedor;
    private javax.swing.JButton btnlimpiardatos;
    private javax.swing.JButton btnmenuprincipal;
    private javax.swing.JButton btnregistrar;
    private javax.swing.JButton btnsalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabladedatos;
    private javax.swing.JTextField txtape;
    private javax.swing.JTextField txtdir;
    private javax.swing.JTextField txtnit;
    private javax.swing.JTextField txtnom;
    private javax.swing.JTextField txttel;
    // End of variables declaration//GEN-END:variables
}
