/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package salsamentaria;

/**
 *
 * @author DFVAL
 */
public class Empleado extends javax.swing.JFrame {

    /**
     * Creates new form Empleado
     */
    public Empleado() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setExtendedState(Login.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtcargoempleado = new javax.swing.JTextField();
        extccempleado = new javax.swing.JTextField();
        txtnomempleado = new javax.swing.JTextField();
        txtapeempleado = new javax.swing.JTextField();
        txttelempleado = new javax.swing.JTextField();
        txtgenempleado = new javax.swing.JTextField();
        btnagregarempleado = new javax.swing.JButton();
        btnbuscarempleado = new javax.swing.JButton();
        btneliminarempleado = new javax.swing.JButton();
        btnsalir = new javax.swing.JButton();
        btnmenuprincipal = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("EMPLEADO");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(190, 20, 130, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("CARGO");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(100, 285, 70, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("APELLIDO");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(100, 170, 80, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 255));
        jLabel4.setText("C.C.");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(110, 75, 40, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 255));
        jLabel5.setText("NOMBRE");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(100, 120, 80, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 255));
        jLabel6.setText("TELEFONO");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(100, 205, 80, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 255));
        jLabel7.setText("GENERO");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(100, 245, 80, 20);
        getContentPane().add(txtcargoempleado);
        txtcargoempleado.setBounds(210, 280, 180, 30);
        getContentPane().add(extccempleado);
        extccempleado.setBounds(210, 80, 180, 30);

        txtnomempleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomempleadoActionPerformed(evt);
            }
        });
        getContentPane().add(txtnomempleado);
        txtnomempleado.setBounds(210, 120, 180, 30);
        getContentPane().add(txtapeempleado);
        txtapeempleado.setBounds(210, 160, 180, 30);
        getContentPane().add(txttelempleado);
        txttelempleado.setBounds(210, 200, 180, 30);
        getContentPane().add(txtgenempleado);
        txtgenempleado.setBounds(210, 240, 180, 30);

        btnagregarempleado.setText("AGREGAR");
        getContentPane().add(btnagregarempleado);
        btnagregarempleado.setBounds(40, 353, 100, 30);

        btnbuscarempleado.setText("BUSCAR");
        getContentPane().add(btnbuscarempleado);
        btnbuscarempleado.setBounds(190, 353, 110, 30);

        btneliminarempleado.setText("ELIMINAR");
        getContentPane().add(btneliminarempleado);
        btneliminarempleado.setBounds(340, 353, 110, 30);

        btnsalir.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnsalir.setText("SALIR");
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnsalir);
        btnsalir.setBounds(60, 450, 80, 30);

        btnmenuprincipal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnmenuprincipal.setText("MENU PRINCIPAL");
        btnmenuprincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnmenuprincipalMouseClicked(evt);
            }
        });
        getContentPane().add(btnmenuprincipal);
        btnmenuprincipal.setBounds(300, 450, 150, 30);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/org-fondo-madera-negro.jpg"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 0, 480, 510);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnomempleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomempleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomempleadoActionPerformed

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
       System.exit(WIDTH);
    }//GEN-LAST:event_btnsalirActionPerformed

    private void btnmenuprincipalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnmenuprincipalMouseClicked
         MENU MN = new MENU();
           MN .setVisible(true);
           dispose();
    }//GEN-LAST:event_btnmenuprincipalMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Empleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Empleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Empleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Empleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Empleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnagregarempleado;
    private javax.swing.JButton btnbuscarempleado;
    private javax.swing.JButton btneliminarempleado;
    private javax.swing.JButton btnmenuprincipal;
    private javax.swing.JButton btnsalir;
    private javax.swing.JTextField extccempleado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtapeempleado;
    private javax.swing.JTextField txtcargoempleado;
    private javax.swing.JTextField txtgenempleado;
    private javax.swing.JTextField txtnomempleado;
    private javax.swing.JTextField txttelempleado;
    // End of variables declaration//GEN-END:variables
}
