/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package salsamentaria;

/**
 *
 * @author DFVAL
 */
public class Producto extends javax.swing.JFrame {

    /**
     * Creates new form Producto
     */
    public Producto() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setExtendedState(Login.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtvalproductos = new javax.swing.JTextField();
        txtcodproductos = new javax.swing.JTextField();
        txtdesproductos = new javax.swing.JTextField();
        txttipoproductos = new javax.swing.JTextField();
        txtcantproductos = new javax.swing.JTextField();
        btnagregarproductos = new javax.swing.JButton();
        btnconsultarproductos = new javax.swing.JButton();
        btneliminarproductos = new javax.swing.JButton();
        btnsalir = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PRODUCTOS");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(200, 30, 130, 22);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 255));
        jLabel3.setText("VALOR");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(140, 280, 60, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 255));
        jLabel4.setText("CODIGO");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(130, 100, 73, 17);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 255));
        jLabel5.setText("DESCRIPCION");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(120, 147, 120, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 255));
        jLabel6.setText("TIPO");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(140, 200, 52, 15);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 255));
        jLabel7.setText("CANTIDAD");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(130, 240, 90, 17);
        getContentPane().add(txtvalproductos);
        txtvalproductos.setBounds(260, 270, 160, 30);
        getContentPane().add(txtcodproductos);
        txtcodproductos.setBounds(260, 90, 160, 30);
        getContentPane().add(txtdesproductos);
        txtdesproductos.setBounds(260, 140, 160, 40);

        txttipoproductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttipoproductosActionPerformed(evt);
            }
        });
        getContentPane().add(txttipoproductos);
        txttipoproductos.setBounds(260, 190, 160, 30);
        getContentPane().add(txtcantproductos);
        txtcantproductos.setBounds(260, 230, 160, 30);

        btnagregarproductos.setText("AGREGAR");
        getContentPane().add(btnagregarproductos);
        btnagregarproductos.setBounds(60, 333, 90, 30);

        btnconsultarproductos.setText("CONSULTAR");
        getContentPane().add(btnconsultarproductos);
        btnconsultarproductos.setBounds(210, 330, 100, 30);

        btneliminarproductos.setText("ELIMINAR");
        getContentPane().add(btneliminarproductos);
        btneliminarproductos.setBounds(360, 330, 100, 30);

        btnsalir.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnsalir.setText("SALIR");
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnsalir);
        btnsalir.setBounds(30, 403, 80, 30);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton2.setText("MENU PRINCIPAL");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(350, 403, 130, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/org-fondo-madera-negro.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 490, 440);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txttipoproductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttipoproductosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttipoproductosActionPerformed

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        System.exit(WIDTH);
    }//GEN-LAST:event_btnsalirActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        MENU MN = new MENU();
           MN .setVisible(true);
           dispose();
    }//GEN-LAST:event_jButton2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Producto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnagregarproductos;
    private javax.swing.JButton btnconsultarproductos;
    private javax.swing.JButton btneliminarproductos;
    private javax.swing.JButton btnsalir;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtcantproductos;
    private javax.swing.JTextField txtcodproductos;
    private javax.swing.JTextField txtdesproductos;
    private javax.swing.JTextField txttipoproductos;
    private javax.swing.JTextField txtvalproductos;
    // End of variables declaration//GEN-END:variables
}
