module Pedidos{
    interface Pedido{
        boolean insertarPedidos(in long idCliente, in wstring nombre, in wstring direccion, in wstring telefono, in wstring estado);
        boolean actualizarPediso(in long idPedidos, in long idClientes, in wstring nombre, in wstring direccion, in wstring telefono, in wstring estado);
        boolean eliminarPedidos(in long idPedidos);
        wstring consultarPedidos(in long idPedidos);
        

        oneway void shoutdown();
    };
};
